#!/usr/bin/env python3
import json
import os
import threading
from concurrent import futures

import grpc

import appfs_adapter_v1_pb2 as pb2
import appfs_adapter_v1_pb2_grpc as pb2_grpc


def _env_int(name: str, default: int) -> int:
    raw = os.getenv(name, "").strip()
    if raw == "":
        return default
    try:
        return int(raw)
    except ValueError:
        return default


def _parse_fail_status_code(raw: str) -> grpc.StatusCode:
    normalized = (raw or "").strip().upper()
    if normalized == "":
        return grpc.StatusCode.UNAVAILABLE
    code = grpc.StatusCode.__members__.get(normalized)
    if code is None:
        return grpc.StatusCode.UNAVAILABLE
    return code


class FaultInjector:
    def __init__(self) -> None:
        self._lock = threading.Lock()
        self.fail_next_submit_action = max(0, _env_int("APPFS_BRIDGE_FAIL_NEXT_SUBMIT_ACTION", 0))
        self.fail_path_prefix = os.getenv("APPFS_BRIDGE_FAIL_PATH_PREFIX", "").strip()
        self.fail_status_code = _parse_fail_status_code(os.getenv("APPFS_BRIDGE_FAIL_GRPC_CODE", ""))
        self.config_path = os.getenv(
            "APPFS_BRIDGE_FAULT_CONFIG_PATH", "/tmp/appfs-bridge-fault-config.json"
        ).strip()
        self._last_config_mtime = None

    def _reload_config_from_file(self) -> None:
        if self.config_path == "":
            return
        try:
            stat = os.stat(self.config_path)
        except OSError:
            return
        mtime = stat.st_mtime
        if self._last_config_mtime == mtime:
            return
        try:
            with open(self.config_path, "r", encoding="utf-8") as f:
                data = json.load(f)
        except Exception:
            return
        try:
            self.fail_next_submit_action = max(0, int(data.get("fail_next_submit_action", 0)))
            self.fail_path_prefix = str(data.get("fail_path_prefix", self.fail_path_prefix)).strip()
            self.fail_status_code = _parse_fail_status_code(
                str(data.get("fail_grpc_code", self.fail_status_code.name))
            )
        except Exception:
            return
        self._last_config_mtime = mtime

    def maybe_fail_submit_action(self, path: str) -> tuple[bool, int]:
        with self._lock:
            self._reload_config_from_file()
            if self.fail_next_submit_action <= 0:
                return (False, 0)
            if self.fail_path_prefix and not path.startswith(self.fail_path_prefix):
                return (False, self.fail_next_submit_action)
            self.fail_next_submit_action -= 1
            return (True, self.fail_next_submit_action)


FAULT_INJECTOR = FaultInjector()


class BridgeService(pb2_grpc.AppfsAdapterBridgeServicer):
    def SubmitAction(self, request: pb2.SubmitActionRequest, context: grpc.ServicerContext):
        path = request.path
        execution_mode = request.execution_mode
        should_fail, remaining = FAULT_INJECTOR.maybe_fail_submit_action(path)
        if should_fail:
            context.abort(
                FAULT_INJECTOR.fail_status_code,
                f"fault injected for path={path}, remaining={remaining}",
            )

        if execution_mode == pb2.EXECUTION_MODE_INLINE:
            if path.endswith("/send_message.act"):
                return pb2.SubmitActionResponse(
                    completed=pb2.CompletedOutcome(content_json=json.dumps("send success"))
                )
            return pb2.SubmitActionResponse(
                completed=pb2.CompletedOutcome(content_json=json.dumps("action completed"))
            )

        terminal = {"ok": True}
        if path.endswith("/download.act"):
            try:
                payload = json.loads(request.payload)
                terminal = {"saved_to": payload.get("target", "unknown")}
            except Exception:
                terminal = {"saved_to": "unknown"}

        return pb2.SubmitActionResponse(
            streaming=pb2.StreamingOutcome(
                accepted_content_json=json.dumps("accepted"),
                progress_content_json=json.dumps({"percent": 50}),
                terminal_content_json=json.dumps(terminal),
                has_accepted_content=True,
                has_progress_content=True,
            )
        )

    def SubmitControlAction(
        self, request: pb2.SubmitControlActionRequest, context: grpc.ServicerContext
    ):
        which = request.WhichOneof("action")

        if which == "paging_fetch_next":
            action = request.paging_fetch_next
            content = {
                "items": [{"id": f"m-{action.page_no}", "text": "generated by grpc bridge"}],
                "page": {
                    "handle_id": action.handle_id,
                    "page_no": action.page_no,
                    "has_more": action.has_more,
                    "mode": "live",
                },
            }
            return pb2.SubmitControlActionResponse(
                completed=pb2.ControlCompletedOutcome(content_json=json.dumps(content))
            )

        if which == "paging_close":
            action = request.paging_close
            content = {"closed": True, "handle_id": action.handle_id}
            return pb2.SubmitControlActionResponse(
                completed=pb2.ControlCompletedOutcome(content_json=json.dumps(content))
            )

        return pb2.SubmitControlActionResponse(
            error=pb2.BridgeError(
                code="NOT_SUPPORTED",
                message=f"unsupported control action: {which}",
                retryable=False,
            )
        )


def main() -> None:
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=8))
    pb2_grpc.add_AppfsAdapterBridgeServicer_to_server(BridgeService(), server)
    server.add_insecure_port("127.0.0.1:50051")
    server.start()
    print("AppFS gRPC bridge listening on 127.0.0.1:50051")
    print(
        "Fault injector: fail_next_submit_action=%d fail_status_code=%s fail_path_prefix=%r"
        % (
            FAULT_INJECTOR.fail_next_submit_action,
            FAULT_INJECTOR.fail_status_code.name,
            FAULT_INJECTOR.fail_path_prefix,
        )
    )
    print(f"Fault config path: {FAULT_INJECTOR.config_path}")
    server.wait_for_termination()


if __name__ == "__main__":
    main()
