#!/bin/sh
set -eu

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
TEMPLATE_DIR="$SCRIPT_DIR/http-bridge/python"

usage() {
    cat <<'EOF'
Usage:
  sh ./examples/appfs/new-adapter.sh <adapter_id>

This generates:
  examples/appfs/adapters/<adapter_id>/python
EOF
}

fail() {
    printf 'FAILED: %s\n' "$*" >&2
    exit 1
}

ADAPTER_ID="${1:-}"
[ -n "$ADAPTER_ID" ] || {
    usage
    exit 2
}

case "$ADAPTER_ID" in
    *[!A-Za-z0-9_-]*)
        fail "adapter_id must match [A-Za-z0-9_-]"
        ;;
esac

TARGET_DIR="$SCRIPT_DIR/adapters/$ADAPTER_ID/python"
[ ! -e "$TARGET_DIR" ] || fail "target already exists: $TARGET_DIR"

mkdir -p "$TARGET_DIR/appfs_http_bridge" "$TARGET_DIR/tests"

cp "$TEMPLATE_DIR/bridge_server.py" "$TARGET_DIR/bridge_server.py"
cp "$TEMPLATE_DIR/run-conformance.sh" "$TARGET_DIR/run-conformance.sh"
cp "$TEMPLATE_DIR/.gitignore" "$TARGET_DIR/.gitignore"

for file in "$TEMPLATE_DIR"/appfs_http_bridge/*.py; do
    cp "$file" "$TARGET_DIR/appfs_http_bridge/"
done
for file in "$TEMPLATE_DIR"/tests/*.py; do
    cp "$file" "$TARGET_DIR/tests/"
done

cat >"$TARGET_DIR/pyproject.toml" <<EOF
[project]
name = "appfs-${ADAPTER_ID}-adapter"
version = "0.1.0"
description = "AppFS adapter scaffold for ${ADAPTER_ID}"
requires-python = ">=3.12"
dependencies = []

[tool.uv]
package = false
EOF

cat >"$TARGET_DIR/README.md" <<EOF
# AppFS Adapter Scaffold: ${ADAPTER_ID}

Generated by:

1. \`examples/appfs/new-adapter.sh\`

## Local Unit Tests

\`\`\`bash
cd examples/appfs/adapters/${ADAPTER_ID}/python
uv run python -m unittest discover -s tests -t . -p "test_*.py"
\`\`\`

## Live Conformance

\`\`\`bash
cd examples/appfs/adapters/${ADAPTER_ID}/python
APPFS_ADAPTER_HTTP_ENDPOINT=http://127.0.0.1:8080 sh ./run-conformance.sh
\`\`\`

## Next Edits

1. Modify \`appfs_http_bridge/mock_aiim.py\` for your domain logic.
2. Keep \`appfs_http_bridge/protocol.py\` behavior aligned with AppFS contracts.
3. Verify \`CT-001 ~ CT-017\` before compatibility claim.
EOF

chmod +x "$TARGET_DIR/run-conformance.sh"

printf 'Generated adapter scaffold:\n%s\n' "$TARGET_DIR"
printf '\nNext:\n'
printf '1. cd %s\n' "$TARGET_DIR"
printf '2. uv run python -m unittest discover -s tests -t . -p "test_*.py"\n'
printf '3. APPFS_ADAPTER_HTTP_ENDPOINT=http://127.0.0.1:8080 sh ./run-conformance.sh\n'
