import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// 四个独立侧边栏对应 Diátaxis 四象限：
//   教程(Tutorials) / 实操指南(How-to) / 参考(Reference) / 原理(Explanation)
// 每个侧边栏由对应子目录自动生成，顺序与目录内 _category_.json + 文件名前缀决定。
// 顺序约定：`NN-slug.md` 的数字前缀即阅读顺序。
const sidebars: SidebarsConfig = {
  tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorials'}],
  howtoSidebar: [{type: 'autogenerated', dirName: 'how-to'}],
  referenceSidebar: [{type: 'autogenerated', dirName: 'reference'}],
  explanationSidebar: [{type: 'autogenerated', dirName: 'explanation'}],
};

export default sidebars;
