#!/bin/sh
set -eu

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
TEMPLATE_DIR="$SCRIPT_DIR/http-bridge/python"

usage() {
    cat <<'EOF'
Usage:
  sh ./examples/appfs/legacy/v1/new-adapter.sh <adapter_id>

This generates:
  examples/appfs/legacy/v1/adapters/<adapter_id>/python
EOF
}

fail() {
    printf 'FAILED: %s\n' "$*" >&2
    exit 1
}

ADAPTER_ID="${1:-}"
[ -n "$ADAPTER_ID" ] || {
    usage
    exit 2
}

case "$ADAPTER_ID" in
    *[!A-Za-z0-9_-]*)
        fail "adapter_id must match [A-Za-z0-9_-]"
        ;;
esac

TARGET_DIR="$SCRIPT_DIR/adapters/$ADAPTER_ID/python"
[ ! -e "$TARGET_DIR" ] || fail "target already exists: $TARGET_DIR"

mkdir -p "$TARGET_DIR/appfs_http_bridge" "$TARGET_DIR/tests"

cp "$TEMPLATE_DIR/bridge_server.py" "$TARGET_DIR/bridge_server.py"
cp "$TEMPLATE_DIR/run-conformance.sh" "$TARGET_DIR/run-conformance.sh"
cp "$TEMPLATE_DIR/.gitignore" "$TARGET_DIR/.gitignore"

for file in "$TEMPLATE_DIR"/appfs_http_bridge/*.py; do
    cp "$file" "$TARGET_DIR/appfs_http_bridge/"
done
for file in "$TEMPLATE_DIR"/tests/*.py; do
    cp "$file" "$TARGET_DIR/tests/"
done

cat >"$TARGET_DIR/pyproject.toml" <<EOF
[project]
name = "appfs-${ADAPTER_ID}-adapter"
version = "0.1.0"
description = "AppFS adapter scaffold for ${ADAPTER_ID}"
requires-python = ">=3.12"
dependencies = []

[tool.uv]
package = false
EOF

cat >"$TARGET_DIR/NODE-MAPPING.md" <<EOF
# AppFS Node Mapping (${ADAPTER_ID})

Fill this table before implementing bridge handlers.

| Node template | Kind | Input/Output mode | Execution mode | Bridge route | Backend handler |
|---|---|---|---|---|---|
| contacts/{contact_id}/send_message.act | action | json | inline | /v1/submit-action | handle_send_message |
| files/{file_id}/download.act | action | json | streaming | /v1/submit-action | handle_download |
| _snapshot/refresh.act | action | json | inline | /v1/submit-action | handle_snapshot_refresh |
| _paging/fetch_next.act | control | json | inline | /v1/submit-control-action | handle_paging_fetch_next |
| _paging/close.act | control | json | inline | /v1/submit-control-action | handle_paging_close |

Checklist:

1. Every declared \`.act\` template in manifest has one handler mapping.
2. No handler exists for undeclared action templates.
3. Control actions and pageable resources are mapped consistently.
EOF

cat >"$TARGET_DIR/README.md" <<EOF
# AppFS Adapter Scaffold: ${ADAPTER_ID}

Generated by:

1. \`examples/appfs/legacy/v1/new-adapter.sh\`

## Local Unit Tests

\`\`\`bash
cd examples/appfs/legacy/v1/adapters/${ADAPTER_ID}/python
uv run python -m unittest discover -s tests -t . -p "test_*.py"
\`\`\`

## Live Conformance

\`\`\`bash
cd examples/appfs/legacy/v1/adapters/${ADAPTER_ID}/python
APPFS_ADAPTER_HTTP_ENDPOINT=http://127.0.0.1:8080 sh ./run-conformance.sh
\`\`\`

To run against a custom app fixture tree:

\`\`\`bash
cd examples/appfs/legacy/v1/adapters/${ADAPTER_ID}/python
APPFS_FIXTURE_DIR=/path/to/appfs-fixture APPFS_APP_ID=${ADAPTER_ID} APPFS_ADAPTER_HTTP_ENDPOINT=http://127.0.0.1:8080 sh ./run-conformance.sh
\`\`\`

## Define Structure First

1. Declare node templates in \`<fixture_root>/${ADAPTER_ID}/_meta/manifest.res.json\`.
2. Create matching \`.act\` sink files and \`.res.json\` / \`.res.jsonl\` resources under \`<fixture_root>/${ADAPTER_ID}/\`.
3. Fill \`NODE-MAPPING.md\` and keep a 1:1 mapping from node templates to backend handlers.

Reference docs:

1. \`docs/v1/APPFS-adapter-structure-mapping-v0.1.md\`
2. \`docs/v1/APPFS-adapter-developer-guide-v0.1.md\`

## Next Edits

1. Fill \`NODE-MAPPING.md\`.
2. Modify \`appfs_http_bridge/mock_aiim.py\` for your domain logic.
3. Keep \`appfs_http_bridge/protocol.py\` behavior aligned with AppFS contracts.
4. Verify \`CT-001 ~ CT-022\` before compatibility claim (enable bridge resilience probe for \`CT-017\`).
EOF

chmod +x "$TARGET_DIR/run-conformance.sh"

printf 'Generated adapter scaffold:\n%s\n' "$TARGET_DIR"
printf '\nNext:\n'
printf '1. cd %s\n' "$TARGET_DIR"
printf '2. edit NODE-MAPPING.md and manifest/app fixture nodes first\n'
printf '3. uv run python -m unittest discover -s tests -t . -p "test_*.py"\n'
printf '4. APPFS_ADAPTER_HTTP_ENDPOINT=http://127.0.0.1:8080 sh ./run-conformance.sh\n'
