use agentfs_sdk::{
    AdapterControlActionV1, AdapterControlOutcomeV1, AdapterErrorV1, AdapterExecutionModeV1,
    AdapterInputModeV1, AdapterStreamingPlanV1, AdapterSubmitOutcomeV1, AppAdapterV1,
    RequestContextV1,
};
use serde_json::{json, Value as JsonValue};

pub(super) struct DemoAppAdapterV1 {
    app_id: String,
}

impl DemoAppAdapterV1 {
    pub(super) fn new(app_id: String) -> Self {
        Self { app_id }
    }
}

impl AppAdapterV1 for DemoAppAdapterV1 {
    fn app_id(&self) -> &str {
        &self.app_id
    }

    fn submit_action(
        &mut self,
        path: &str,
        payload: &str,
        _input_mode: AdapterInputModeV1,
        execution_mode: AdapterExecutionModeV1,
        _ctx: &RequestContextV1,
    ) -> std::result::Result<AdapterSubmitOutcomeV1, AdapterErrorV1> {
        match execution_mode {
            AdapterExecutionModeV1::Inline => {
                let content = if path.ends_with("/send_message.act") {
                    json!("send success")
                } else {
                    json!("action completed")
                };
                Ok(AdapterSubmitOutcomeV1::Completed { content })
            }
            AdapterExecutionModeV1::Streaming => {
                let terminal = if path.ends_with("/download.act") {
                    if let Ok(json) = serde_json::from_str::<JsonValue>(payload) {
                        if let Some(target) = json.get("target").and_then(|v| v.as_str()) {
                            json!({ "saved_to": target })
                        } else {
                            json!({ "saved_to": "unknown" })
                        }
                    } else {
                        json!({ "saved_to": "unknown" })
                    }
                } else {
                    json!("action completed")
                };

                Ok(AdapterSubmitOutcomeV1::Streaming {
                    plan: AdapterStreamingPlanV1 {
                        accepted_content: Some(json!("accepted")),
                        progress_content: Some(json!({ "percent": 50 })),
                        terminal_content: terminal,
                    },
                })
            }
        }
    }

    fn submit_control_action(
        &mut self,
        _path: &str,
        action: AdapterControlActionV1,
        _ctx: &RequestContextV1,
    ) -> std::result::Result<AdapterControlOutcomeV1, AdapterErrorV1> {
        match action {
            AdapterControlActionV1::PagingFetchNext {
                handle_id,
                page_no,
                has_more,
            } => Ok(AdapterControlOutcomeV1::Completed {
                content: json!({
                    "items": [
                        {
                            "id": format!("m-{}", page_no),
                            "text": "generated by appfs adapter"
                        }
                    ],
                    "page": {
                        "handle_id": handle_id,
                        "page_no": page_no,
                        "has_more": has_more,
                        "mode": "snapshot"
                    }
                }),
            }),
            AdapterControlActionV1::PagingClose { handle_id } => {
                Ok(AdapterControlOutcomeV1::Completed {
                    content: json!({
                        "closed": true,
                        "handle_id": handle_id
                    }),
                })
            }
        }
    }
}
