pub(super) const ERR_PAGER_HANDLE_NOT_FOUND: &str = "PAGER_HANDLE_NOT_FOUND";
pub(super) const ERR_PAGER_HANDLE_EXPIRED: &str = "PAGER_HANDLE_EXPIRED";
pub(super) const ERR_PAGER_HANDLE_CLOSED: &str = "PAGER_HANDLE_CLOSED";
pub(super) const ERR_PERMISSION_DENIED: &str = "PERMISSION_DENIED";
pub(super) const ERR_INVALID_ARGUMENT: &str = "INVALID_ARGUMENT";
pub(super) const ERR_INVALID_PAYLOAD: &str = "INVALID_PAYLOAD";
pub(super) const ERR_SNAPSHOT_TOO_LARGE: &str = "SNAPSHOT_TOO_LARGE";
pub(super) const ERR_CACHE_MISS_EXPAND_FAILED: &str = "CACHE_MISS_EXPAND_FAILED";
