from __future__ import annotations

import json
import urllib.request
from dataclasses import dataclass, field


@dataclass
class JsonPlaceholderBackend:
    base_url: str = "https://jsonplaceholder.typicode.com"
    timeout_sec: float = 5.0
    closed_handles: set[str] = field(default_factory=set)

    def submit_action(self, path: str, execution_mode: str, payload: str) -> dict[str, object]:
        if execution_mode == "inline":
            return self._submit_inline(path, payload)
        return self._submit_streaming(path, payload)

    def submit_control_fetch_next(
        self,
        handle_id: str,
        page_no: int,
        has_more: bool,
    ) -> dict[str, object]:
        # Reuse deterministic paging behavior for contract stability.
        return {
            "kind": "completed",
            "content": {
                "items": [{"id": f"m-{page_no}", "text": "generated by jsonplaceholder backend"}],
                "page": {
                    "handle_id": handle_id,
                    "page_no": page_no,
                    "has_more": has_more,
                    "mode": "live",
                },
            },
        }

    def submit_control_close(self, handle_id: str) -> dict[str, object]:
        self.closed_handles.add(handle_id)
        return {
            "kind": "completed",
            "content": {"closed": True, "handle_id": handle_id},
        }

    def _submit_inline(self, path: str, payload: str) -> dict[str, object]:
        if path.endswith("/send_message.act"):
            message = payload.strip()
            try:
                parsed = json.loads(payload)
                if isinstance(parsed, dict) and isinstance(parsed.get("text"), str):
                    message = parsed["text"].strip()
            except Exception:
                message = payload.strip()

            body = {
                "title": "appfs-send-message",
                "body": message,
                "contact_id": self._extract_contact_id(path),
                "userId": 1,
            }
            posted = self._post_json("/posts", body)
            return {
                "kind": "completed",
                "content": {
                    "provider": "jsonplaceholder",
                    "result": "send success",
                    "post_id": posted.get("id"),
                    "contact_id": body["contact_id"],
                },
            }

        return {
            "kind": "completed",
            "content": {"provider": "jsonplaceholder", "result": "action completed"},
        }

    def _submit_streaming(self, path: str, payload: str) -> dict[str, object]:
        terminal_content: dict[str, object] = {
            "provider": "jsonplaceholder",
            "ok": True,
        }
        if path.endswith("/download.act"):
            target = "unknown"
            try:
                parsed = json.loads(payload)
                if isinstance(parsed, dict) and isinstance(parsed.get("target"), str):
                    target = parsed["target"]
            except Exception:
                target = "unknown"

            doc = self._get_json("/posts/1")
            terminal_content = {
                "provider": "jsonplaceholder",
                "saved_to": target,
                "source_id": doc.get("id"),
                "source_title": doc.get("title", ""),
            }

        return {
            "kind": "streaming",
            "plan": {
                "accepted_content": "accepted",
                "progress_content": {"percent": 50, "provider": "jsonplaceholder"},
                "terminal_content": terminal_content,
            },
        }

    def _extract_contact_id(self, path: str) -> str:
        parts = [p for p in path.strip("/").split("/") if p]
        if len(parts) >= 3 and parts[0] == "contacts":
            return parts[1]
        return "unknown"

    def _post_json(self, path: str, body: dict[str, object]) -> dict[str, object]:
        url = f"{self.base_url}{path}"
        req = urllib.request.Request(
            url,
            data=json.dumps(body).encode("utf-8"),
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=self.timeout_sec) as resp:
            raw = resp.read().decode("utf-8")
            parsed = json.loads(raw)
            if not isinstance(parsed, dict):
                raise RuntimeError(f"unexpected POST response shape at {url}")
            return parsed

    def _get_json(self, path: str) -> dict[str, object]:
        url = f"{self.base_url}{path}"
        req = urllib.request.Request(url, method="GET")
        with urllib.request.urlopen(req, timeout=self.timeout_sec) as resp:
            raw = resp.read().decode("utf-8")
            parsed = json.loads(raw)
            if not isinstance(parsed, dict):
                raise RuntimeError(f"unexpected GET response shape at {url}")
            return parsed
