from __future__ import annotations

import json
from dataclasses import dataclass, field


@dataclass
class MockAiimBackend:
    closed_handles: set[str] = field(default_factory=set)

    def submit_action(self, path: str, execution_mode: str, payload: str) -> dict[str, object]:
        if execution_mode == "inline":
            return self._submit_inline(path, payload)
        return self._submit_streaming(path, payload)

    def submit_control_fetch_next(
        self,
        handle_id: str,
        page_no: int,
        has_more: bool,
    ) -> dict[str, object]:
        return {
            "kind": "completed",
            "content": {
                "items": [{"id": f"m-{page_no}", "text": "generated by python bridge"}],
                "page": {
                    "handle_id": handle_id,
                    "page_no": page_no,
                    "has_more": has_more,
                    "mode": "live",
                },
            },
        }

    def submit_control_close(self, handle_id: str) -> dict[str, object]:
        self.closed_handles.add(handle_id)
        return {
            "kind": "completed",
            "content": {"closed": True, "handle_id": handle_id},
        }

    def _submit_inline(self, path: str, payload: str) -> dict[str, object]:
        if path.endswith("/send_message.act"):
            if payload.strip() == "":
                return {"kind": "completed", "content": "send failed: empty message"}
            return {"kind": "completed", "content": "send success"}
        return {"kind": "completed", "content": "action completed"}

    def _submit_streaming(self, path: str, payload: str) -> dict[str, object]:
        terminal_content: dict[str, object] = {"ok": True}
        if path.endswith("/download.act"):
            target = "unknown"
            try:
                parsed = json.loads(payload)
                if isinstance(parsed, dict):
                    parsed_target = parsed.get("target", "unknown")
                    if isinstance(parsed_target, str) and parsed_target.strip() != "":
                        target = parsed_target
            except Exception:
                target = "unknown"
            terminal_content = {"saved_to": target}

        return {
            "kind": "streaming",
            "plan": {
                "accepted_content": "accepted",
                "progress_content": {"percent": 50},
                "terminal_content": terminal_content,
            },
        }
