#!/bin/sh
set -eu

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
TEMPLATE_DIR="$SCRIPT_DIR/templates/http-python"

usage() {
    cat <<'EOF'
Usage:
  sh ./examples/appfs/new-connector.sh <connector_id>

This generates:
  examples/appfs/connectors/<connector_id>/http-python
EOF
}

fail() {
    printf 'FAILED: %s\n' "$*" >&2
    exit 1
}

CONNECTOR_ID="${1:-}"
[ -n "$CONNECTOR_ID" ] || {
    usage
    exit 2
}

case "$CONNECTOR_ID" in
    *[!A-Za-z0-9_-]*)
        fail "connector_id must match [A-Za-z0-9_-]"
        ;;
esac

TARGET_DIR="$SCRIPT_DIR/connectors/$CONNECTOR_ID/http-python"
[ ! -e "$TARGET_DIR" ] || fail "target already exists: $TARGET_DIR"

mkdir -p "$SCRIPT_DIR/connectors/$CONNECTOR_ID"
cp -R "$TEMPLATE_DIR" "$TARGET_DIR"

cat >"$TARGET_DIR/pyproject.toml" <<EOF
[project]
name = "appfs-${CONNECTOR_ID}-connector"
version = "0.1.0"
description = "AppFS HTTP connector scaffold for ${CONNECTOR_ID}"
requires-python = ">=3.12"
dependencies = []

[tool.uv]
package = false
EOF

cat >"$TARGET_DIR/CONNECTOR-MAPPING.md" <<EOF
# AppFS Connector Mapping (${CONNECTOR_ID})

Map your product surface to the canonical AppFS connector behaviors before you write code.

## Structure

1. Initial app tree returned by \`get_app_structure\`
2. Scope transitions returned by \`refresh_app_structure\`
3. Connector-owned prefixes to reconcile

## Snapshot Resources

| Path template | Source API / query | Chunking strategy | Max bytes | Notes |
|---|---|---|---|---|
| chats/{id}/messages.res.jsonl | TODO | TODO | TODO | TODO |

## Live Resources

| Path template | Source API / query | Cursor / handle model | Notes |
|---|---|---|---|
| feed/recommendations.res.json | TODO | TODO | TODO |

## Actions

| Path template | Source API / command | Idempotency key | Notes |
|---|---|---|---|
| contacts/{contact_id}/send_message.act | TODO | TODO | TODO |

## Checklist

1. Every declared resource/action in structure output maps to one backend handler.
2. Snapshot resources are readable via ordinary file reads without requiring \`/_snapshot/refresh.act\`.
3. Scope changes prune old connector-owned paths and publish new ones.
4. Unit tests cover structure bootstrap, scope refresh, snapshot fetch, live page, and submit action.
EOF

cat >"$TARGET_DIR/README.md" <<EOF
# AppFS Connector Scaffold: ${CONNECTOR_ID}

Generated by:

1. \`examples/appfs/new-connector.sh\`

This scaffold starts from the current AppFS \`AppConnector\` path.

## Local Unit Tests

\`\`\`bash
cd examples/appfs/connectors/${CONNECTOR_ID}/http-python
uv run python -m unittest discover -s tests -t . -p "test_*.py"
\`\`\`

## Live Conformance

\`\`\`bash
cd examples/appfs/connectors/${CONNECTOR_ID}/http-python
APPFS_ADAPTER_HTTP_ENDPOINT=http://127.0.0.1:8080 sh ./run-conformance.sh
\`\`\`

## Start Here

1. Fill \`CONNECTOR-MAPPING.md\`.
2. Replace the demo behavior in \`appfs_http_bridge/mock_aiim.py\` with your domain logic.
3. Keep \`appfs_http_bridge/protocol.py\` aligned with the canonical connector contract.
4. Verify structure bootstrap, scope refresh, snapshot reads, live paging, and submit action.

## Current Runtime Model

The recommended runtime entry is:

\`\`\`bash
agentfs appfs up <id-or-path> <mountpoint>
\`\`\`

Then register the app through \`/_appfs/register_app.act\`.

Main references:

1. \`docs/v4/README.md\`
2. \`docs/v4/APPFS-v0.4-AppStructureSync-ADR.zh-CN.md\`
3. \`docs/v4/APPFS-v0.4-Connector结构接口.zh-CN.md\`
EOF

chmod +x "$TARGET_DIR/run-conformance.sh"

printf 'Generated connector scaffold:\n%s\n' "$TARGET_DIR"
printf '\nNext:\n'
printf '1. cd %s\n' "$TARGET_DIR"
printf '2. edit CONNECTOR-MAPPING.md first\n'
printf '3. uv run python -m unittest discover -s tests -t . -p "test_*.py"\n'
printf '4. APPFS_ADAPTER_HTTP_ENDPOINT=http://127.0.0.1:8080 sh ./run-conformance.sh\n'
