use crate::{
    ActionExecutionMode, ActionStreamingPlan, AdapterControlActionV1, AdapterControlOutcomeV1,
    AdapterErrorV1, AdapterExecutionModeV1, AdapterInputModeV1, AdapterSnapshotMetaV1,
    AdapterStreamingPlanV1, AdapterSubmitOutcomeV1, AppAdapterV1, AppConnector, AppStructureNode,
    AppStructureNodeKind, AppStructureSnapshot, AppStructureSyncReason, AppStructureSyncResult,
    AuthStatus, ConnectorContext, ConnectorError, ConnectorInfo, ConnectorTransport,
    FetchLivePageRequest, FetchLivePageResponse, FetchSnapshotChunkRequest,
    FetchSnapshotChunkResponse, GetAppStructureRequest, GetAppStructureResponse, HealthStatus,
    LiveMode, LivePageInfo, RefreshAppStructureRequest, RefreshAppStructureResponse,
    RequestContextV1, SnapshotMeta, SnapshotRecord, SnapshotResume, SubmitActionOutcome,
    SubmitActionRequest, SubmitActionResponse,
};
use serde_json::{json, Value as JsonValue};
use std::time::Duration;

/// Reference demo adapter implementation for AppFS v0.1.
///
/// This adapter is intentionally simple and deterministic so runtime and
/// conformance flows can be validated without app-specific backends.
pub struct DemoAppAdapterV1 {
    app_id: String,
}

impl DemoAppAdapterV1 {
    pub fn new(app_id: String) -> Self {
        Self { app_id }
    }
}

impl AppAdapterV1 for DemoAppAdapterV1 {
    fn app_id(&self) -> &str {
        &self.app_id
    }

    fn submit_action(
        &mut self,
        path: &str,
        payload: &str,
        _input_mode: AdapterInputModeV1,
        execution_mode: AdapterExecutionModeV1,
        _ctx: &RequestContextV1,
    ) -> std::result::Result<AdapterSubmitOutcomeV1, AdapterErrorV1> {
        match execution_mode {
            AdapterExecutionModeV1::Inline => {
                let content = if path.ends_with("/send_message.act") {
                    json!("send success")
                } else {
                    json!("action completed")
                };
                Ok(AdapterSubmitOutcomeV1::Completed { content })
            }
            AdapterExecutionModeV1::Streaming => {
                let terminal = if path.ends_with("/download.act") {
                    if let Ok(json) = serde_json::from_str::<JsonValue>(payload) {
                        if let Some(target) = json.get("target").and_then(|v| v.as_str()) {
                            json!({ "saved_to": target })
                        } else {
                            json!({ "saved_to": "unknown" })
                        }
                    } else {
                        json!({ "saved_to": "unknown" })
                    }
                } else {
                    json!("action completed")
                };

                Ok(AdapterSubmitOutcomeV1::Streaming {
                    plan: AdapterStreamingPlanV1 {
                        accepted_content: Some(json!("accepted")),
                        progress_content: Some(json!({ "percent": 50 })),
                        terminal_content: terminal,
                    },
                })
            }
        }
    }

    fn prewarm_snapshot_meta(
        &mut self,
        resource_path: &str,
        timeout: Duration,
    ) -> std::result::Result<AdapterSnapshotMetaV1, AdapterErrorV1> {
        let timeout_ms = (timeout.as_millis().max(1)).min(u128::from(u64::MAX)) as u64;
        let delay_ms = std::env::var("APPFS_PREWARM_DELAY_MS")
            .ok()
            .and_then(|raw| raw.parse::<u64>().ok())
            .unwrap_or(0);

        if delay_ms > timeout_ms {
            std::thread::sleep(Duration::from_millis(timeout_ms));
            return Err(AdapterErrorV1::Rejected {
                code: "TIMEOUT".to_string(),
                message: format!(
                    "prewarm timeout resource={resource_path} delay_ms={delay_ms} timeout_ms={timeout_ms}"
                ),
                retryable: true,
            });
        }

        if delay_ms > 0 {
            std::thread::sleep(Duration::from_millis(delay_ms));
        }

        Ok(AdapterSnapshotMetaV1 {
            size_bytes: Some(5000),
            revision: Some("demo-v1".to_string()),
            ttl_sec: Some(60),
        })
    }

    fn submit_control_action(
        &mut self,
        _path: &str,
        action: AdapterControlActionV1,
        _ctx: &RequestContextV1,
    ) -> std::result::Result<AdapterControlOutcomeV1, AdapterErrorV1> {
        match action {
            AdapterControlActionV1::PagingFetchNext {
                handle_id,
                page_no,
                has_more,
            } => Ok(AdapterControlOutcomeV1::Completed {
                content: json!({
                    "items": [
                        {
                            "id": format!("m-{}", page_no),
                            "text": "generated by appfs adapter"
                        }
                    ],
                    "page": {
                        "handle_id": handle_id,
                        "page_no": page_no,
                        "has_more": has_more,
                        "mode": "live"
                    }
                }),
            }),
            AdapterControlActionV1::PagingClose { handle_id } => {
                Ok(AdapterControlOutcomeV1::Completed {
                    content: json!({
                        "closed": true,
                        "handle_id": handle_id
                    }),
                })
            }
        }
    }
}

/// Reference demo connector implementation for the canonical AppFS connector trait.
///
/// This demo connector is intentionally deterministic and transport-neutral.
pub struct DemoAppConnector {
    app_id: String,
}

impl DemoAppConnector {
    pub fn new(app_id: String) -> Self {
        Self { app_id }
    }

    fn err(code: &str, message: impl Into<String>, retryable: bool) -> ConnectorError {
        ConnectorError {
            code: code.to_string(),
            message: message.into(),
            retryable,
            details: None,
        }
    }

    fn is_snapshot_chat_001(resource_path: &str) -> bool {
        resource_path.ends_with("/chats/chat-001/messages.res.jsonl")
    }

    fn is_snapshot_chat_long(resource_path: &str) -> bool {
        resource_path.ends_with("/chats/chat-long/messages.res.jsonl")
    }

    fn is_snapshot_chat_oversize(resource_path: &str) -> bool {
        resource_path.ends_with("/chats/chat-oversize/messages.res.jsonl")
    }

    fn emit_chat_records(start: usize, end: usize) -> Vec<SnapshotRecord> {
        (start..=end)
            .map(|idx| SnapshotRecord {
                record_key: format!("rk-{idx:03}"),
                ordering_key: format!("ok-{idx:03}"),
                line: json!({
                    "id": format!("m-{idx:03}"),
                    "text": format!("demo message {idx:03}"),
                }),
            })
            .collect()
    }

    fn action_manifest(template: &str, execution_mode: &str) -> JsonValue {
        json!({
            "template": template,
            "kind": "action",
            "input_mode": "json",
            "execution_mode": execution_mode,
        })
    }

    fn snapshot_manifest(template: &str, max_materialized_bytes: usize) -> JsonValue {
        json!({
            "template": template,
            "kind": "resource",
            "output_mode": "jsonl",
            "snapshot": {
                "max_materialized_bytes": max_materialized_bytes,
                "prewarm": true,
                "prewarm_timeout_ms": 5000,
                "read_through_timeout_ms": 10000,
                "on_timeout": "return_stale"
            }
        })
    }

    fn live_manifest(template: &str) -> JsonValue {
        json!({
            "template": template,
            "kind": "resource",
            "output_mode": "json",
            "paging": {
                "enabled": true,
                "mode": "live"
            }
        })
    }

    fn base_structure_nodes(scope: Option<&str>) -> Vec<AppStructureNode> {
        let mut nodes = vec![
            AppStructureNode {
                path: "_meta".to_string(),
                kind: AppStructureNodeKind::Directory,
                manifest_entry: None,
                seed_content: None,
                mutable: false,
                scope: None,
            },
            AppStructureNode {
                path: "contacts".to_string(),
                kind: AppStructureNodeKind::Directory,
                manifest_entry: None,
                seed_content: None,
                mutable: false,
                scope: None,
            },
            AppStructureNode {
                path: "contacts/zhangsan".to_string(),
                kind: AppStructureNodeKind::Directory,
                manifest_entry: None,
                seed_content: None,
                mutable: false,
                scope: None,
            },
            AppStructureNode {
                path: "contacts/zhangsan/send_message.act".to_string(),
                kind: AppStructureNodeKind::ActionFile,
                manifest_entry: Some(Self::action_manifest(
                    "contacts/{contact_id}/send_message.act",
                    "inline",
                )),
                seed_content: None,
                mutable: true,
                scope: None,
            },
            AppStructureNode {
                path: "feed".to_string(),
                kind: AppStructureNodeKind::Directory,
                manifest_entry: None,
                seed_content: None,
                mutable: false,
                scope: None,
            },
            AppStructureNode {
                path: "feed/recommendations.res.json".to_string(),
                kind: AppStructureNodeKind::LiveResource,
                manifest_entry: Some(Self::live_manifest("feed/recommendations.res.json")),
                seed_content: Some(
                    json!({"items":[],"page":{"handle_id":"","page_no":0,"has_more":true,"mode":"live"}}),
                ),
                mutable: false,
                scope: None,
            },
            AppStructureNode {
                path: "_paging".to_string(),
                kind: AppStructureNodeKind::Directory,
                manifest_entry: None,
                seed_content: None,
                mutable: false,
                scope: None,
            },
            AppStructureNode {
                path: "_app".to_string(),
                kind: AppStructureNodeKind::Directory,
                manifest_entry: None,
                seed_content: None,
                mutable: false,
                scope: None,
            },
            AppStructureNode {
                path: "_paging/fetch_next.act".to_string(),
                kind: AppStructureNodeKind::ActionFile,
                manifest_entry: Some(Self::action_manifest("_paging/fetch_next.act", "inline")),
                seed_content: None,
                mutable: true,
                scope: None,
            },
            AppStructureNode {
                path: "_paging/close.act".to_string(),
                kind: AppStructureNodeKind::ActionFile,
                manifest_entry: Some(Self::action_manifest("_paging/close.act", "inline")),
                seed_content: None,
                mutable: true,
                scope: None,
            },
            AppStructureNode {
                path: "_app/enter_scope.act".to_string(),
                kind: AppStructureNodeKind::ActionFile,
                manifest_entry: Some(Self::action_manifest("_app/enter_scope.act", "inline")),
                seed_content: None,
                mutable: true,
                scope: None,
            },
            AppStructureNode {
                path: "_app/refresh_structure.act".to_string(),
                kind: AppStructureNodeKind::ActionFile,
                manifest_entry: Some(Self::action_manifest(
                    "_app/refresh_structure.act",
                    "inline",
                )),
                seed_content: None,
                mutable: true,
                scope: None,
            },
        ];

        match scope {
            Some("chat-long") => {
                nodes.push(AppStructureNode {
                    path: "chats".to_string(),
                    kind: AppStructureNodeKind::Directory,
                    manifest_entry: None,
                    seed_content: None,
                    mutable: false,
                    scope: Some("chat-long".to_string()),
                });
                nodes.push(AppStructureNode {
                    path: "chats/chat-long".to_string(),
                    kind: AppStructureNodeKind::Directory,
                    manifest_entry: None,
                    seed_content: None,
                    mutable: false,
                    scope: Some("chat-long".to_string()),
                });
                nodes.push(AppStructureNode {
                    path: "chats/chat-long/messages.res.jsonl".to_string(),
                    kind: AppStructureNodeKind::SnapshotResource,
                    manifest_entry: Some(Self::snapshot_manifest(
                        "chats/chat-long/messages.res.jsonl",
                        1024,
                    )),
                    seed_content: None,
                    mutable: false,
                    scope: Some("chat-long".to_string()),
                });
            }
            _ => {
                nodes.push(AppStructureNode {
                    path: "chats".to_string(),
                    kind: AppStructureNodeKind::Directory,
                    manifest_entry: None,
                    seed_content: None,
                    mutable: false,
                    scope: Some("chat-001".to_string()),
                });
                nodes.push(AppStructureNode {
                    path: "chats/chat-001".to_string(),
                    kind: AppStructureNodeKind::Directory,
                    manifest_entry: None,
                    seed_content: None,
                    mutable: false,
                    scope: Some("chat-001".to_string()),
                });
                nodes.push(AppStructureNode {
                    path: "chats/chat-001/messages.res.jsonl".to_string(),
                    kind: AppStructureNodeKind::SnapshotResource,
                    manifest_entry: Some(Self::snapshot_manifest(
                        "chats/chat-001/messages.res.jsonl",
                        10 * 1024 * 1024,
                    )),
                    seed_content: None,
                    mutable: false,
                    scope: Some("chat-001".to_string()),
                });
            }
        }

        nodes
    }

    fn structure_snapshot(
        &self,
        scope: Option<&str>,
    ) -> std::result::Result<AppStructureSnapshot, ConnectorError> {
        let active_scope = match scope {
            None | Some("chat-001") => "chat-001".to_string(),
            Some("chat-long") => "chat-long".to_string(),
            Some(other) => {
                return Err(Self::err(
                    "STRUCTURE_SCOPE_INVALID",
                    format!("unknown structure scope: {other}"),
                    false,
                ));
            }
        };
        Ok(AppStructureSnapshot {
            app_id: self.app_id.clone(),
            revision: format!("demo-structure-{active_scope}"),
            active_scope: Some(active_scope.clone()),
            ownership_prefixes: vec![
                "_meta".to_string(),
                "contacts".to_string(),
                "feed".to_string(),
                "chats".to_string(),
                "_paging".to_string(),
                "_app".to_string(),
            ],
            nodes: Self::base_structure_nodes(Some(&active_scope)),
        })
    }
}

impl AppConnector for DemoAppConnector {
    fn connector_id(&self) -> std::result::Result<ConnectorInfo, ConnectorError> {
        Ok(ConnectorInfo {
            connector_id: format!("demo-connector-{}", self.app_id),
            version: "0.5.0-demo".to_string(),
            app_id: self.app_id.clone(),
            transport: ConnectorTransport::InProcess,
            supports_snapshot: true,
            supports_live: true,
            supports_action: true,
            optional_features: vec!["demo_mode".to_string()],
        })
    }

    fn health(
        &mut self,
        ctx: &ConnectorContext,
    ) -> std::result::Result<HealthStatus, ConnectorError> {
        if ctx.trace_id.as_deref() == Some("force-upstream-unavailable") {
            return Err(Self::err(
                "UPSTREAM_UNAVAILABLE",
                "upstream endpoint is unavailable",
                true,
            ));
        }

        let auth_status = if ctx.trace_id.as_deref() == Some("force-auth-expired") {
            AuthStatus::Expired
        } else {
            AuthStatus::Valid
        };

        Ok(HealthStatus {
            healthy: auth_status == AuthStatus::Valid,
            auth_status,
            message: Some("demo connector healthy".to_string()),
            checked_at: "2026-03-24T00:00:00Z".to_string(),
        })
    }

    fn prewarm_snapshot_meta(
        &mut self,
        resource_path: &str,
        timeout: Duration,
        _ctx: &ConnectorContext,
    ) -> std::result::Result<SnapshotMeta, ConnectorError> {
        if resource_path.contains("/forbidden/") {
            return Err(Self::err(
                "PERMISSION_DENIED",
                "resource is forbidden",
                false,
            ));
        }

        let timeout_ms = (timeout.as_millis().max(1)).min(u128::from(u64::MAX)) as u64;
        let delay_ms = std::env::var("APPFS_PREWARM_DELAY_MS")
            .ok()
            .and_then(|raw| raw.parse::<u64>().ok())
            .unwrap_or(0);

        if delay_ms > timeout_ms {
            std::thread::sleep(Duration::from_millis(timeout_ms));
            return Err(Self::err(
                "TIMEOUT",
                format!(
                    "prewarm timeout resource={resource_path} delay_ms={delay_ms} timeout_ms={timeout_ms}"
                ),
                true,
            ));
        }

        if delay_ms > 0 {
            std::thread::sleep(Duration::from_millis(delay_ms));
        }

        Ok(SnapshotMeta {
            size_bytes: Some(5000),
            revision: Some("demo-connector".to_string()),
            last_modified: Some("2026-03-24T00:00:00Z".to_string()),
            item_count: Some(2),
        })
    }

    fn fetch_snapshot_chunk(
        &mut self,
        request: FetchSnapshotChunkRequest,
        _ctx: &ConnectorContext,
    ) -> std::result::Result<FetchSnapshotChunkResponse, ConnectorError> {
        if request.budget_bytes == 0 {
            return Err(Self::err(
                "INVALID_ARGUMENT",
                "budget_bytes must be > 0",
                false,
            ));
        }
        if request.resource_path.contains("too_large")
            && !Self::is_snapshot_chat_oversize(&request.resource_path)
        {
            return Err(Self::err(
                "SNAPSHOT_TOO_LARGE",
                "snapshot exceeds configured limit",
                false,
            ));
        }

        let (records, next_cursor, has_more) =
            if Self::is_snapshot_chat_long(&request.resource_path) {
                return Err(Self::err(
                    "UPSTREAM_UNAVAILABLE",
                    "snapshot source unavailable for /chats/chat-long/messages.res.jsonl",
                    true,
                ));
            } else if Self::is_snapshot_chat_oversize(&request.resource_path) {
                match request.resume {
                    SnapshotResume::Start => (
                        Self::emit_chat_records(1, 12),
                        Some("oversize-cursor-12".to_string()),
                        true,
                    ),
                    SnapshotResume::Cursor(cursor) => {
                        if cursor == "cursor-invalid" {
                            return Err(Self::err(
                                "INVALID_ARGUMENT",
                                "resume cursor is invalid",
                                false,
                            ));
                        }
                        if cursor == "oversize-cursor-12" {
                            (Self::emit_chat_records(13, 24), None, false)
                        } else {
                            return Err(Self::err(
                                "INVALID_ARGUMENT",
                                "resume cursor is unknown",
                                false,
                            ));
                        }
                    }
                    SnapshotResume::Offset(offset) => (
                        vec![SnapshotRecord {
                            record_key: format!("rk-offset-{offset}"),
                            ordering_key: format!("ok-offset-{offset}"),
                            line: json!({"id":"m-offset","offset":offset}),
                        }],
                        None,
                        false,
                    ),
                }
            } else if Self::is_snapshot_chat_001(&request.resource_path) {
                match request.resume {
                    SnapshotResume::Start => (
                        Self::emit_chat_records(1, 40),
                        Some("chat-001-cursor-40".to_string()),
                        true,
                    ),
                    SnapshotResume::Cursor(cursor) => {
                        if cursor == "cursor-invalid" {
                            return Err(Self::err(
                                "INVALID_ARGUMENT",
                                "resume cursor is invalid",
                                false,
                            ));
                        }
                        if cursor == "chat-001-cursor-40" {
                            (
                                Self::emit_chat_records(41, 80),
                                Some("chat-001-cursor-80".to_string()),
                                true,
                            )
                        } else if cursor == "chat-001-cursor-80" {
                            (Self::emit_chat_records(81, 100), None, false)
                        } else {
                            return Err(Self::err(
                                "INVALID_ARGUMENT",
                                "resume cursor is unknown",
                                false,
                            ));
                        }
                    }
                    SnapshotResume::Offset(offset) => (
                        vec![SnapshotRecord {
                            record_key: format!("rk-offset-{offset}"),
                            ordering_key: format!("ok-offset-{offset}"),
                            line: json!({"id":"m-offset","offset":offset}),
                        }],
                        None,
                        false,
                    ),
                }
            } else {
                match request.resume {
                    SnapshotResume::Start => (
                        vec![
                            SnapshotRecord {
                                record_key: "rk-001".to_string(),
                                ordering_key: "ok-001".to_string(),
                                line: json!({"id":"m-1","text":"hello"}),
                            },
                            SnapshotRecord {
                                record_key: "rk-002".to_string(),
                                ordering_key: "ok-002".to_string(),
                                line: json!({"id":"m-2","text":"world"}),
                            },
                        ],
                        Some("cursor-2".to_string()),
                        true,
                    ),
                    SnapshotResume::Cursor(cursor) => {
                        if cursor == "cursor-invalid" {
                            return Err(Self::err(
                                "INVALID_ARGUMENT",
                                "resume cursor is invalid",
                                false,
                            ));
                        }
                        if cursor == "cursor-2" {
                            (
                                vec![SnapshotRecord {
                                    record_key: "rk-003".to_string(),
                                    ordering_key: "ok-003".to_string(),
                                    line: json!({"id":"m-3","text":"done"}),
                                }],
                                None,
                                false,
                            )
                        } else {
                            return Err(Self::err(
                                "INVALID_ARGUMENT",
                                "resume cursor is unknown",
                                false,
                            ));
                        }
                    }
                    SnapshotResume::Offset(offset) => {
                        if request.resource_path.contains("no-offset") {
                            return Err(Self::err(
                                "NOT_SUPPORTED",
                                "offset resume is not supported for this resource",
                                false,
                            ));
                        }
                        (
                            vec![SnapshotRecord {
                                record_key: format!("rk-offset-{offset}"),
                                ordering_key: format!("ok-offset-{offset}"),
                                line: json!({"id":"m-offset","offset":offset}),
                            }],
                            None,
                            false,
                        )
                    }
                }
            };

        let emitted_bytes = records.iter().fold(0_u64, |acc, record| {
            let line_bytes = serde_json::to_vec(&record.line)
                .map(|v| v.len() as u64 + 1)
                .unwrap_or(0);
            acc.saturating_add(line_bytes)
        });

        Ok(FetchSnapshotChunkResponse {
            records,
            emitted_bytes,
            next_cursor,
            has_more,
            revision: Some("demo-connector".to_string()),
        })
    }

    fn fetch_live_page(
        &mut self,
        request: FetchLivePageRequest,
        _ctx: &ConnectorContext,
    ) -> std::result::Result<FetchLivePageResponse, ConnectorError> {
        if request.page_size == 0 {
            return Err(Self::err(
                "INVALID_ARGUMENT",
                "page_size must be > 0",
                false,
            ));
        }
        if request.cursor.as_deref() == Some("invalid") {
            return Err(Self::err("CURSOR_INVALID", "cursor is invalid", false));
        }
        if request.cursor.as_deref() == Some("expired") {
            return Err(Self::err("CURSOR_EXPIRED", "cursor has expired", false));
        }

        let page_no = if request.cursor.as_deref() == Some("cursor-1") {
            2
        } else {
            1
        };
        let has_more = page_no == 1;
        let next_cursor = if has_more {
            Some("cursor-1".to_string())
        } else {
            None
        };

        Ok(FetchLivePageResponse {
            items: vec![json!({
                "id": format!("item-{page_no}"),
                "resource": request.resource_path,
            })],
            page: LivePageInfo {
                handle_id: request
                    .handle_id
                    .unwrap_or_else(|| "demo-live-handle-1".to_string()),
                page_no,
                has_more,
                mode: LiveMode::Live,
                expires_at: Some("2026-03-24T01:00:00Z".to_string()),
                next_cursor,
                retry_after_ms: None,
            },
        })
    }

    fn submit_action(
        &mut self,
        request: SubmitActionRequest,
        ctx: &ConnectorContext,
    ) -> std::result::Result<SubmitActionResponse, ConnectorError> {
        if request.path.contains("invalid_payload") {
            return Err(Self::err(
                "INVALID_PAYLOAD",
                "payload does not match schema",
                false,
            ));
        }
        if request.path.contains("rate_limited") {
            return Err(Self::err("RATE_LIMITED", "upstream rate limited", true));
        }

        let outcome = match request.execution_mode {
            ActionExecutionMode::Inline => SubmitActionOutcome::Completed {
                content: json!({
                    "ok": true,
                    "path": request.path,
                    "echo": request.payload,
                }),
            },
            ActionExecutionMode::Streaming => SubmitActionOutcome::Streaming {
                plan: ActionStreamingPlan {
                    accepted_content: Some(json!({"state":"accepted"})),
                    progress_content: Some(json!({"percent":50})),
                    terminal_content: json!({"ok": true}),
                },
            },
        };

        Ok(SubmitActionResponse {
            request_id: ctx.request_id.clone(),
            estimated_duration_ms: Some(120),
            outcome,
        })
    }
    fn get_app_structure(
        &mut self,
        request: GetAppStructureRequest,
        _ctx: &ConnectorContext,
    ) -> std::result::Result<GetAppStructureResponse, ConnectorError> {
        let snapshot = self.structure_snapshot(None)?;
        if request.known_revision.as_deref() == Some(snapshot.revision.as_str()) {
            return Ok(GetAppStructureResponse {
                result: AppStructureSyncResult::Unchanged {
                    app_id: request.app_id,
                    revision: snapshot.revision,
                    active_scope: snapshot.active_scope,
                },
            });
        }

        Ok(GetAppStructureResponse {
            result: AppStructureSyncResult::Snapshot { snapshot },
        })
    }

    fn refresh_app_structure(
        &mut self,
        request: RefreshAppStructureRequest,
        _ctx: &ConnectorContext,
    ) -> std::result::Result<RefreshAppStructureResponse, ConnectorError> {
        if matches!(request.reason, AppStructureSyncReason::EnterScope)
            && request.target_scope.is_none()
        {
            return Err(Self::err(
                "STRUCTURE_SCOPE_INVALID",
                "target_scope is required for enter_scope refresh",
                false,
            ));
        }
        let snapshot = self.structure_snapshot(request.target_scope.as_deref())?;
        if request.known_revision.as_deref() == Some(snapshot.revision.as_str()) {
            return Ok(RefreshAppStructureResponse {
                result: AppStructureSyncResult::Unchanged {
                    app_id: request.app_id,
                    revision: snapshot.revision,
                    active_scope: snapshot.active_scope,
                },
            });
        }

        Ok(RefreshAppStructureResponse {
            result: AppStructureSyncResult::Snapshot { snapshot },
        })
    }
}

#[cfg(test)]
mod tests {
    use super::{DemoAppAdapterV1, DemoAppConnector};
    use crate::{
        ActionExecutionMode, AdapterControlActionV1, AdapterControlOutcomeV1,
        AdapterExecutionModeV1, AdapterInputModeV1, AdapterSubmitOutcomeV1, AppAdapterV1,
        AppConnector, AppStructureSyncReason, ConnectorContext, FetchLivePageRequest,
        FetchSnapshotChunkRequest, GetAppStructureRequest, RefreshAppStructureRequest,
        RequestContextV1, SnapshotResume, SubmitActionOutcome, SubmitActionRequest,
    };
    use std::sync::{Mutex, OnceLock};
    use std::time::Duration;

    fn ctx() -> RequestContextV1 {
        RequestContextV1 {
            app_id: "aiim".to_string(),
            session_id: "sess-test".to_string(),
            request_id: "req-1".to_string(),
            client_token: Some("tok-1".to_string()),
        }
    }

    fn connector_ctx(trace_id: Option<&str>) -> ConnectorContext {
        ConnectorContext {
            app_id: "aiim".to_string(),
            session_id: "sess-test".to_string(),
            request_id: "req-connector-1".to_string(),
            client_token: Some("tok-connector-1".to_string()),
            trace_id: trace_id.map(|v| v.to_string()),
        }
    }

    fn env_lock() -> &'static Mutex<()> {
        static LOCK: OnceLock<Mutex<()>> = OnceLock::new();
        LOCK.get_or_init(|| Mutex::new(()))
    }

    #[test]
    fn demo_adapter_inline_action() {
        let mut adapter = DemoAppAdapterV1::new("aiim".to_string());
        let result = adapter
            .submit_action(
                "/contacts/zhangsan/send_message.act",
                r#"{"text":"hello"}"#,
                AdapterInputModeV1::Json,
                AdapterExecutionModeV1::Inline,
                &ctx(),
            )
            .expect("inline action should succeed");
        match result {
            AdapterSubmitOutcomeV1::Completed { content } => {
                assert_eq!(content, "send success");
            }
            _ => panic!("expected inline completed"),
        }
    }

    #[test]
    fn demo_adapter_streaming_action() {
        let mut adapter = DemoAppAdapterV1::new("aiim".to_string());
        let result = adapter
            .submit_action(
                "/files/file-001/download.act",
                r#"{"target":"/tmp/a.bin"}"#,
                AdapterInputModeV1::Json,
                AdapterExecutionModeV1::Streaming,
                &ctx(),
            )
            .expect("streaming action should succeed");
        match result {
            AdapterSubmitOutcomeV1::Streaming { plan } => {
                assert!(plan.accepted_content.is_some());
                assert!(plan.progress_content.is_some());
                assert_eq!(plan.terminal_content["saved_to"], "/tmp/a.bin");
            }
            _ => panic!("expected streaming outcome"),
        }
    }

    #[test]
    fn demo_adapter_control_action() {
        let mut adapter = DemoAppAdapterV1::new("aiim".to_string());
        let result = adapter
            .submit_control_action(
                "/_paging/close.act",
                AdapterControlActionV1::PagingClose {
                    handle_id: "ph_abc".to_string(),
                },
                &ctx(),
            )
            .expect("control action should succeed");
        match result {
            AdapterControlOutcomeV1::Completed { content } => {
                assert_eq!(content["closed"], true);
                assert_eq!(content["handle_id"], "ph_abc");
            }
        }
    }

    #[test]
    fn demo_adapter_prewarm_snapshot_meta() {
        let mut adapter = DemoAppAdapterV1::new("aiim".to_string());
        let meta = adapter
            .prewarm_snapshot_meta(
                "/chats/chat-001/messages.res.jsonl",
                Duration::from_millis(50),
            )
            .expect("prewarm should succeed");
        assert_eq!(meta.size_bytes, Some(5000));
        assert_eq!(meta.revision.as_deref(), Some("demo-v1"));
    }

    #[test]
    fn demo_connector_info_health_and_prewarm() {
        let mut connector = DemoAppConnector::new("aiim".to_string());

        let info = connector
            .connector_id()
            .expect("connector info should succeed");
        assert_eq!(info.app_id, "aiim");
        assert!(info.supports_snapshot);
        assert!(info.supports_live);
        assert!(info.supports_action);

        let health = connector
            .health(&connector_ctx(None))
            .expect("health should succeed");
        assert!(health.healthy);

        let expired = connector
            .health(&connector_ctx(Some("force-auth-expired")))
            .expect("auth expired health status should still return payload");
        assert!(!expired.healthy);

        let _guard = env_lock().lock().expect("env lock should be acquirable");
        std::env::remove_var("APPFS_PREWARM_DELAY_MS");
        let meta = connector
            .prewarm_snapshot_meta(
                "/chats/chat-001/messages.res.jsonl",
                Duration::from_millis(20),
                &connector_ctx(None),
            )
            .expect("prewarm should succeed");
        assert_eq!(meta.revision.as_deref(), Some("demo-connector"));
    }

    #[test]
    fn demo_connector_health_error_path() {
        let mut connector = DemoAppConnector::new("aiim".to_string());
        let err = connector
            .health(&connector_ctx(Some("force-upstream-unavailable")))
            .expect_err("health error path should be mapped");
        assert_eq!(err.code, "UPSTREAM_UNAVAILABLE");
        assert!(err.retryable);
    }

    #[test]
    fn demo_connector_prewarm_error_paths() {
        let mut connector = DemoAppConnector::new("aiim".to_string());

        let forbidden = connector
            .prewarm_snapshot_meta(
                "/forbidden/chats/chat-001/messages.res.jsonl",
                Duration::from_millis(20),
                &connector_ctx(None),
            )
            .expect_err("forbidden resource must return explicit permission error");
        assert_eq!(forbidden.code, "PERMISSION_DENIED");

        let _guard = env_lock().lock().expect("env lock should be acquirable");
        std::env::set_var("APPFS_PREWARM_DELAY_MS", "30");
        let timeout = connector
            .prewarm_snapshot_meta(
                "/chats/chat-001/messages.res.jsonl",
                Duration::from_millis(5),
                &connector_ctx(None),
            )
            .expect_err("timeout path should be mapped");
        std::env::remove_var("APPFS_PREWARM_DELAY_MS");

        assert_eq!(timeout.code, "TIMEOUT");
        assert!(timeout.retryable);
    }

    #[test]
    fn demo_connector_prewarm_uses_canonical_env() {
        let mut connector = DemoAppConnector::new("aiim".to_string());
        let _guard = env_lock().lock().expect("env lock should be acquirable");

        std::env::set_var("APPFS_PREWARM_DELAY_MS", "30");

        let timeout = connector
            .prewarm_snapshot_meta(
                "/chats/chat-001/messages.res.jsonl",
                Duration::from_millis(5),
                &connector_ctx(None),
            )
            .expect_err("canonical env should drive timeout path");

        std::env::remove_var("APPFS_PREWARM_DELAY_MS");
        assert_eq!(timeout.code, "TIMEOUT");
        assert!(timeout.retryable);
    }

    #[test]
    fn demo_connector_snapshot_success_and_error() {
        let mut connector = DemoAppConnector::new("aiim".to_string());

        let chunk = connector
            .fetch_snapshot_chunk(
                FetchSnapshotChunkRequest {
                    resource_path: "/chats/chat-generic/messages.res.jsonl".to_string(),
                    resume: SnapshotResume::Start,
                    budget_bytes: 1024,
                },
                &connector_ctx(None),
            )
            .expect("snapshot chunk should succeed");
        assert!(!chunk.records.is_empty());
        assert!(chunk.emitted_bytes > 0);

        let err = connector
            .fetch_snapshot_chunk(
                FetchSnapshotChunkRequest {
                    resource_path: "/chats/no-offset/messages.res.jsonl".to_string(),
                    resume: SnapshotResume::Offset(10),
                    budget_bytes: 1024,
                },
                &connector_ctx(None),
            )
            .expect_err("offset resume should be rejected for unsupported resource");
        assert_eq!(err.code, "NOT_SUPPORTED");
        assert!(!err.retryable);

        let cursor_err = connector
            .fetch_snapshot_chunk(
                FetchSnapshotChunkRequest {
                    resource_path: "/chats/chat-001/messages.res.jsonl".to_string(),
                    resume: SnapshotResume::Cursor("cursor-unknown".to_string()),
                    budget_bytes: 1024,
                },
                &connector_ctx(None),
            )
            .expect_err("unknown cursor must be rejected explicitly");
        assert_eq!(cursor_err.code, "INVALID_ARGUMENT");
        assert!(!cursor_err.retryable);
    }

    #[test]
    fn demo_connector_snapshot_chat_001_materializes_100_records() {
        let mut connector = DemoAppConnector::new("aiim".to_string());
        let mut resume = SnapshotResume::Start;
        let mut total = 0usize;
        let mut chunks = 0usize;
        loop {
            let chunk = connector
                .fetch_snapshot_chunk(
                    FetchSnapshotChunkRequest {
                        resource_path: "/chats/chat-001/messages.res.jsonl".to_string(),
                        resume,
                        budget_bytes: 1_048_576,
                    },
                    &connector_ctx(None),
                )
                .expect("chat-001 chunk fetch should succeed");
            total += chunk.records.len();
            chunks += 1;
            if !chunk.has_more {
                break;
            }
            let cursor = chunk
                .next_cursor
                .expect("has_more=true must include next_cursor");
            resume = SnapshotResume::Cursor(cursor);
        }
        assert_eq!(chunks, 3);
        assert_eq!(total, 100);
    }

    #[test]
    fn demo_connector_snapshot_chat_long_returns_upstream_error() {
        let mut connector = DemoAppConnector::new("aiim".to_string());
        let err = connector
            .fetch_snapshot_chunk(
                FetchSnapshotChunkRequest {
                    resource_path: "/chats/chat-long/messages.res.jsonl".to_string(),
                    resume: SnapshotResume::Start,
                    budget_bytes: 1024,
                },
                &connector_ctx(None),
            )
            .expect_err("chat-long must fail through upstream error path");
        assert_eq!(err.code, "UPSTREAM_UNAVAILABLE");
        assert!(err.retryable);
    }

    #[test]
    fn demo_connector_snapshot_chat_oversize_yields_large_materializable_chunk() {
        let mut connector = DemoAppConnector::new("aiim".to_string());
        let first = connector
            .fetch_snapshot_chunk(
                FetchSnapshotChunkRequest {
                    resource_path: "/chats/chat-oversize/messages.res.jsonl".to_string(),
                    resume: SnapshotResume::Start,
                    budget_bytes: 1_048_576,
                },
                &connector_ctx(None),
            )
            .expect("oversize snapshot start chunk should succeed");
        assert!(first.has_more);
        let second = connector
            .fetch_snapshot_chunk(
                FetchSnapshotChunkRequest {
                    resource_path: "/chats/chat-oversize/messages.res.jsonl".to_string(),
                    resume: SnapshotResume::Cursor(
                        first
                            .next_cursor
                            .expect("oversize start chunk must include cursor"),
                    ),
                    budget_bytes: 1_048_576,
                },
                &connector_ctx(None),
            )
            .expect("oversize snapshot second chunk should succeed");
        assert!(!second.has_more);
        let total_bytes = first.emitted_bytes.saturating_add(second.emitted_bytes);
        assert!(total_bytes > 128);
    }

    #[test]
    fn demo_connector_live_success_and_cursor_errors() {
        let mut connector = DemoAppConnector::new("aiim".to_string());

        let page = connector
            .fetch_live_page(
                FetchLivePageRequest {
                    resource_path: "/chats/chat-001/messages.res.json".to_string(),
                    handle_id: None,
                    cursor: None,
                    page_size: 20,
                },
                &connector_ctx(None),
            )
            .expect("live page should succeed");
        assert_eq!(page.page.page_no, 1);
        assert!(page.page.has_more);

        let invalid = connector
            .fetch_live_page(
                FetchLivePageRequest {
                    resource_path: "/chats/chat-001/messages.res.json".to_string(),
                    handle_id: None,
                    cursor: Some("invalid".to_string()),
                    page_size: 20,
                },
                &connector_ctx(None),
            )
            .expect_err("invalid cursor must return explicit error");
        assert_eq!(invalid.code, "CURSOR_INVALID");

        let expired = connector
            .fetch_live_page(
                FetchLivePageRequest {
                    resource_path: "/chats/chat-001/messages.res.json".to_string(),
                    handle_id: None,
                    cursor: Some("expired".to_string()),
                    page_size: 20,
                },
                &connector_ctx(None),
            )
            .expect_err("expired cursor must return explicit error");
        assert_eq!(expired.code, "CURSOR_EXPIRED");
    }

    #[test]
    fn demo_connector_submit_success_and_error() {
        let mut connector = DemoAppConnector::new("aiim".to_string());

        let inline = connector
            .submit_action(
                SubmitActionRequest {
                    path: "/contacts/zhangsan/send_message.act".to_string(),
                    payload: serde_json::json!({"text":"hello"}),
                    execution_mode: ActionExecutionMode::Inline,
                },
                &connector_ctx(None),
            )
            .expect("inline submit should succeed");
        match inline.outcome {
            SubmitActionOutcome::Completed { content } => {
                assert_eq!(content["ok"], true);
            }
            _ => panic!("expected completed outcome"),
        }

        let streaming = connector
            .submit_action(
                SubmitActionRequest {
                    path: "/contacts/zhangsan/upload.act".to_string(),
                    payload: serde_json::json!({"target":"x"}),
                    execution_mode: ActionExecutionMode::Streaming,
                },
                &connector_ctx(None),
            )
            .expect("streaming submit should succeed");
        match streaming.outcome {
            SubmitActionOutcome::Streaming { plan } => {
                assert!(plan.accepted_content.is_some());
                assert!(plan.progress_content.is_some());
            }
            _ => panic!("expected streaming outcome"),
        }

        let err = connector
            .submit_action(
                SubmitActionRequest {
                    path: "/contacts/zhangsan/invalid_payload.act".to_string(),
                    payload: serde_json::json!({"x":"y"}),
                    execution_mode: ActionExecutionMode::Inline,
                },
                &connector_ctx(None),
            )
            .expect_err("invalid payload should return mapped error");
        assert_eq!(err.code, "INVALID_PAYLOAD");
        assert!(!err.retryable);
    }

    #[test]
    fn demo_connector_structure_get_and_refresh() {
        let mut connector = DemoAppConnector::new("aiim".to_string());

        let initial = connector
            .get_app_structure(
                GetAppStructureRequest {
                    app_id: "aiim".to_string(),
                    known_revision: None,
                },
                &connector_ctx(None),
            )
            .expect("initial structure should succeed");
        let initial_revision = match initial.result {
            crate::AppStructureSyncResult::Snapshot { snapshot } => {
                assert_eq!(snapshot.active_scope.as_deref(), Some("chat-001"));
                assert!(snapshot
                    .nodes
                    .iter()
                    .any(|node| node.path == "chats/chat-001/messages.res.jsonl"));
                snapshot.revision
            }
            _ => panic!("expected structure snapshot"),
        };

        let unchanged = connector
            .get_app_structure(
                GetAppStructureRequest {
                    app_id: "aiim".to_string(),
                    known_revision: Some(initial_revision.clone()),
                },
                &connector_ctx(None),
            )
            .expect("unchanged structure should succeed");
        assert!(matches!(
            unchanged.result,
            crate::AppStructureSyncResult::Unchanged { .. }
        ));

        let refreshed = connector
            .refresh_app_structure(
                RefreshAppStructureRequest {
                    app_id: "aiim".to_string(),
                    known_revision: Some(initial_revision),
                    reason: AppStructureSyncReason::EnterScope,
                    target_scope: Some("chat-long".to_string()),
                    trigger_action_path: Some("/_app/enter_scope.act".to_string()),
                },
                &connector_ctx(None),
            )
            .expect("scope refresh should succeed");
        match refreshed.result {
            crate::AppStructureSyncResult::Snapshot { snapshot } => {
                assert_eq!(snapshot.active_scope.as_deref(), Some("chat-long"));
                assert!(snapshot
                    .nodes
                    .iter()
                    .any(|node| node.path == "chats/chat-long/messages.res.jsonl"));
                assert!(!snapshot
                    .nodes
                    .iter()
                    .any(|node| node.path == "chats/chat-001/messages.res.jsonl"));
            }
            _ => panic!("expected refreshed structure snapshot"),
        }

        let invalid_scope = connector
            .refresh_app_structure(
                RefreshAppStructureRequest {
                    app_id: "aiim".to_string(),
                    known_revision: None,
                    reason: AppStructureSyncReason::EnterScope,
                    target_scope: Some("missing-scope".to_string()),
                    trigger_action_path: None,
                },
                &connector_ctx(None),
            )
            .expect_err("unknown scope should be rejected");
        assert_eq!(invalid_scope.code, "STRUCTURE_SCOPE_INVALID");
    }
}
